### ISSUE TITLE
能否后续版本支持点击”应用更改“提示

### ISSUE THREAD

**Issue by SuperYuJi** [ilgnefz/once_power#4]
能否后续版本支持点击”应用更改“提示”共有n个文件，成功修改n个文件命名“的类似提示

**Comment by ilgnefz** [comment]
完成后右下角有弹窗提示

**Comment by ilgnefz** [comment]
![微信截图_20240817120251](https://github.com/user-attachments/assets/309aa14e-5d97-4bb8-9454-40c870c00874)
