### ISSUE TITLE
对嵌套文件夹重命名

### ISSUE THREAD

**Issue by Eyion** [ilgnefz/once_power#5]
文件夹下还有子文件夹（甚至更多层的嵌套），只能对添加的那级文件夹生效。

**Comment by ilgnefz** [comment]
意思是勾选了添加文件夹后除了自身文件及也要把文件夹下的子文件夹也列出来吗

**Comment by Eyion** [comment]
是的，或者能够选择列出或者不列出

**Comment by ilgnefz** [comment]
已更新该功能

**Comment by ilgnefz** [comment]
更新了新版本，现在可以根据文件的扩展名格式来筛选添加的文件了
