### ISSUE TITLE
如何添加进右键，将选中文件进行批量重命名，每次拖东也很麻烦，求 更

### ISSUE THREAD

**Issue by SaltNego** [ilgnefz/once_power#8]
如何添加进右键，将选中文件进行批量重命名，每次拖东也很麻烦

**Comment by ilgnefz** [comment]
已更新

**Comment by SaltNego** [comment]
![image](https://github.com/user-attachments/assets/9f60a76a-6c07-4b2d-b9e5-069e696ff034)
选择右键添加到oncepower时，就会跳出这个选项，并不会启动本软件并添加选中文件

**Comment by ilgnefz** [comment]
你选择右键添加到OncePower时是启动了软件的还是没启动？因为Windows的限制，在未启动软件时我设置只能选择文件夹和文件夹内没选择文件时的右键有添加到OncePower的菜单，否则只能通过发送到来添加多个文件，软件启动后可以自由选择文件添加。你这种情况可以试下重新关闭再打开该功能。该功能需要写入注册表实现，所以启动该功能后每次打开和关闭都会修改注册表。

**Comment by SaltNego** [comment]
软件启动或者没有启动，右键添加文件夹和文件都没法添加到该软件里面，我刚才都试了

**Comment by SaltNego** [comment]
![image](https://github.com/user-attachments/assets/d63e5308-b6d9-44a8-b825-f77b797b9d6d)
 右键文件夹显示这个

**Comment by ilgnefz** [comment]
能录制gif（可以使用ScreenToGif）或者使用过程的右键截图给我看下吗

**Comment by SaltNego** [comment]
![screenshots](https://github.com/user-attachments/assets/894a09bf-c235-4e01-ab8a-8558eaa53bc4)
好的

**Comment by ilgnefz** [comment]
打开注册表，在地址栏输入计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shell\OncePower截图看看

**Comment by SaltNego** [comment]
![image](https://github.com/user-attachments/assets/75879914-67cb-4592-86f7-5a4332ad4c0a)

**Comment by SaltNego** [comment]
![image](https://github.com/user-attachments/assets/12f74e80-fa88-4c42-a881-887f479cf928)

**Comment by ilgnefz** [comment]
![微信截图_20241017105854](https://github.com/user-attachments/assets/b430d62e-6546-480c-9ac8-7513a9afd4cd)
![微信截图_20241017105907](https://github.com/user-attachments/assets/37c1d7d0-e8fc-431f-b627-7e1af6b35322)
正确的应该是这样

**Comment by SaltNego** [comment]
![image](https://github.com/user-attachments/assets/daf800f8-066f-41f0-bd9a-3bf9efe7f5b2)
![image](https://github.com/user-attachments/assets/df2ef961-b329-48bc-a25f-42ff024b79fb)
改成这样后文件可以了，文件夹还是报错下面这个样子
![screengif241017 113017](https://github.com/user-attachments/assets/d141a13c-6bf4-4700-b041-b0bcd1fff586)

**Comment by ilgnefz** [comment]
计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shell\OncePower这个是文件夹的，改了没啥用，因为在软件关闭后我设置这两个注册表会被删除，不清楚为啥你那注册表的值是错误的，你使用的是免安装的还是那个安装的程序包。我等下更新一个新的版本，你把这个功能先关闭然后删除软件重新下一个试试

**Comment by ilgnefz** [comment]
已更新，我重装了一个win11的系统也无法复现你的问题，如果新版本还是有同样的错误你把软件里那个功能关闭，我给你写一个注册表的文件把这些值注册进去

**Comment by SaltNego** [comment]
还是不行不知道哪里出了问题，你写个注册表我试试
我的路径是

"D:\Program Files\OncePower\once_power.exe"

**Comment by ilgnefz** [comment]
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shell\OncePower]
@="添加到 OncePower（运行时）"
"Icon"="D:\\Program Files\\OncePower\\once_power.exe,0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shell\OncePower\command]
@="D:\\Program Files\\OncePower\\once_power.exe shortcut_menu_extender --key OncePower --path \"%1\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shell\OncePower]
@="添加到 OncePower（运行时）"
"Icon"="D:\\Program Files\\OncePower\\once_power.exe,0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shell\OncePower\command]
@="D:\\Program Files\\OncePower\\once_power.exe shortcut_menu_extender --key OncePower --path \"%1\""

[HKEY_CURRENT_USER\Software\Classes\Directory\shell\OncePower]
@="添加所有子文件到 OncePower"
"Icon"="D:\\Program Files\\OncePower\\once_power.exe"

[HKEY_CURRENT_USER\Software\Classes\Directory\shell\OncePower\command]
@="D:\\Program Files\\OncePower\\once_power.exe \"%V\""

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\OncePower]
@="添加所有子文件到 OncePower"
"Icon"="D:\\Program Files\\OncePower\\once_power.exe"

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\OncePower\command]
@="D:\\Program Files\\OncePower\\once_power.exe \"%V\""
```

**Comment by ilgnefz** [comment]
我好像知道是为啥了，因为你的目录Program Files中间有个空格，注册表注册因为路径的空格被截断了，换个没有空格的安装路径就行了

**Comment by ilgnefz** [comment]
我看一下在代码中能不能解决这个问题

**Comment by SaltNego** [comment]
代码中你应该有个函数截断了，估计稍微调整下就行

**Comment by ilgnefz** [comment]
已修复，现在应该可以了
